### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by kevintransp** [ThatZiv/z-loadscreen#2]
I have got this error in the console.

nui://z-loadscreen/app.js:79, Uncaught TypeError: Cannot set property 'innerHTML' of null

**Comment by ThatZiv** [comment]
Is it actually causing any functional problems?

**Comment by kevintransp** [comment]
I geuss not, no that i can see.

**Comment by ThatZiv** [comment]
So then what is the *real* issue

**Comment by kevintransp** [comment]
I dont like errors because it is not nessesary.

**Comment by How-Bout-No** [comment]
The error doesn’t cause any problems. If you really just want the error gone, just remove line 79 in app.js and you’ll be fine...

**Comment by ThatZiv** [comment]
No, that will most likely break the progress bar if you delete it.

**Comment by How-Bout-No** [comment]
Interestingly enough, removing lines 79, 57, and 68 eliminated any errors in the console and did not have any effect on the progress bar.
(At least on my end)

**Comment by ThatZiv** [comment]
> Interestingly enough, removing lines 79, 57, and 68 eliminated any errors in the console and did not have any effect on the progress bar.
> (At least on my end)

Guess that fixes the console errors...Gonna close this now. Thanks @How-Bout-No once again.

**Comment by kevintransp** [comment]
Thanks wil change that end test again
